spring:
  application:
    name: im-demo


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.92.115.8:3306/im?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  # classpath: 表示去 resources 目录下找
  public-key: classpath:certs/app.pub
  private-key: classpath:certs/app.key